import {
  BarChart3,
  BookOpen,
  CalendarDays,
  ClipboardCheck,
  CreditCard,
  FileText,
  GraduationCap,
  Megaphone,
  ReceiptIndianRupee,
  School,
  Settings,
  Users,
} from 'lucide-react'

export const MODULES = {
  students: {
    title: 'Students',
    eyebrow: 'STUDENT MANAGEMENT',
    description: 'Manage admissions, profiles, classes, guardians and student records.',
    icon: Users,
    permissionByRole: { principal: 'students.manage', teacher: 'students.view.assigned', accountant: 'students.view.basic' },
    stats: [['Total students', '1,245', '+4.8%'], ['Active today', '1,186', '+2.1%'], ['New admissions', '42', '+12.4%'], ['Pending documents', '18', '-6.3%']],
    columns: ['Student', 'Class', 'Guardian', 'Attendance', 'Status'],
    rows: [
      ['Aarav Sharma', '10-A', 'Rohit Sharma', '96%', 'Active'],
      ['Anaya Patel', '9-B', 'Neha Patel', '92%', 'Active'],
      ['Vivaan Mehta', '8-A', 'Kunal Mehta', '88%', 'Active'],
      ['Diya Shah', '10-B', 'Amit Shah', '79%', 'Review'],
      ['Arjun Rao', '7-C', 'Priya Rao', '94%', 'Active'],
    ],
    actions: ['Add student', 'Import students', 'Export list'],
  },
  'teacher-assignments': {
    title: 'Teacher Assignments',
    eyebrow: 'ACADEMIC ALLOCATION',
    description: 'Assign teachers to multiple classes, sections and subjects by academic year.',
    icon: GraduationCap,
    permissionByRole: { principal: 'teachers.manage' },
    stats: [],
    columns: [],
    rows: [],
    actions: ['Assign teacher', 'Edit assignment'],
  },
  teachers: {
    title: 'Teachers', eyebrow: 'STAFF MANAGEMENT', description: 'Manage faculty profiles, subjects, workload and teaching assignments.', icon: GraduationCap,
    permissionByRole: { principal: 'teachers.manage' },
    stats: [['Teaching staff', '68', '+2.1%'], ['Present today', '64', '+3.4%'], ['On leave', '4', '-20%'], ['Open positions', '3', '+1']],
    columns: ['Teacher', 'Department', 'Classes', 'Attendance', 'Status'],
    rows: [['Priya Nair', 'Mathematics', '8', '98%', 'Active'], ['Rahul Verma', 'Science', '7', '96%', 'Active'], ['Sneha Kapoor', 'English', '6', '94%', 'Active'], ['Amit Joshi', 'Computer', '5', '91%', 'Leave'], ['Meera Iyer', 'Social Science', '7', '97%', 'Active']],
    actions: ['Add teacher', 'Assign subject', 'Export faculty'],
  },
  classes: {
    title: 'Classes & Sections', eyebrow: 'ACADEMICS', description: 'Organise grades, sections, class teachers and student strength.', icon: School,
    permissionByRole: { principal: 'classes.manage', teacher: 'classes.view.assigned' },
    stats: [['Total classes', '36', '+2'], ['Sections', '72', '+4'], ['Students', '1,245', '+4.8%'], ['Avg. strength', '34.6', '-1.2%']],
    columns: ['Class', 'Class teacher', 'Students', 'Room', 'Status'],
    rows: [['10-A', 'Priya Nair', '36', '204', 'Active'], ['10-B', 'Rahul Verma', '34', '205', 'Active'], ['9-A', 'Sneha Kapoor', '35', '301', 'Active'], ['8-A', 'Amit Joshi', '32', '102', 'Active'], ['7-C', 'Meera Iyer', '31', '103', 'Active']],
    actions: ['Create class', 'Assign teacher', 'Manage sections'],
  },
  subjects: {
    title: 'Subjects', eyebrow: 'ACADEMIC SETUP', description: 'Manage subjects, codes, teachers and class-wise curriculum mapping.', icon: BookOpen,
    permissionByRole: { principal: 'subjects.manage' },
    stats: [['Subjects', '42', '+3'], ['Core subjects', '24', ''], ['Electives', '18', '+2'], ['Assigned teachers', '61', '+4']],
    columns: ['Subject', 'Code', 'Classes', 'Teacher', 'Status'],
    rows: [['Mathematics', 'MAT', '6-10', 'Priya Nair', 'Active'], ['Science', 'SCI', '6-10', 'Rahul Verma', 'Active'], ['English', 'ENG', '1-10', 'Sneha Kapoor', 'Active'], ['Computer Science', 'CS', '6-10', 'Amit Joshi', 'Active'], ['Social Science', 'SST', '6-10', 'Meera Iyer', 'Active']],
    actions: ['Add subject', 'Map curriculum', 'Assign teachers'],
  },
  timetable: {
    title: 'Timetable', eyebrow: 'SCHOOL SCHEDULE', description: 'Plan periods, rooms, teacher availability and daily schedules.', icon: CalendarDays,
    permissionByRole: { principal: 'timetable.manage', teacher: 'timetable.view.assigned', student: 'timetable.view.own', parent: 'timetable.view.children' },
    stats: [['Periods today', '288', '+4'], ['Free periods', '31', '-2'], ['Room usage', '86%', '+5.2%'], ['Conflicts', '0', '']],
    columns: ['Time', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    rows: [['08:00', 'Assembly', 'Mathematics', 'Science', 'English'], ['09:00', 'Mathematics', 'English', 'Computer', 'Science'], ['10:00', 'Science', 'Social Science', 'Mathematics', 'Computer'], ['11:30', 'English', 'Science', 'Social Science', 'Mathematics'], ['13:00', 'Activity', 'Mathematics', 'English', 'Sports']],
    actions: ['Create timetable', 'Check conflicts', 'Print schedule'],
  },
  attendance: {
    title: 'Attendance', eyebrow: 'DAILY OPERATIONS', description: 'Monitor student and staff attendance with class-wise insights.', icon: ClipboardCheck,
    permissionByRole: { principal: 'attendance.manage', teacher: 'attendance.manage.assigned', student: 'attendance.view.own', parent: 'attendance.view.children' },
    stats: [['Today', '92.4%', '+1.7%'], ['Present', '1,151', '+24'], ['Absent', '67', '-18'], ['Late', '27', '-5']],
    columns: ['Class', 'Present', 'Absent', 'Late', 'Attendance'],
    rows: [['10-A', '34', '1', '1', '94.4%'], ['10-B', '31', '2', '1', '91.2%'], ['9-A', '33', '2', '0', '94.3%'], ['8-A', '29', '3', '0', '90.6%'], ['7-C', '30', '1', '0', '96.8%']],
    actions: ['Mark attendance', 'View report', 'Export report'],
  },
  'class-attendance': {
    title: 'Class Attendance', eyebrow: 'DAILY STUDENT ATTENDANCE', description: 'Mark and review daily attendance for your assigned classes and sections.', icon: ClipboardCheck,
    permissionByRole: { teacher: 'attendance.manage.assigned' },
    stats: [], columns: [], rows: [], actions: ['Mark all present', 'Save attendance'],
  },
  fees: {
    title: 'Fees & Payments', eyebrow: 'FINANCE', description: 'Track fee collections, dues, receipts and payment status.', icon: CreditCard,
    permissionByRole: { principal: 'fees.manage', accountant: 'fees.manage', student: 'fees.view.own', parent: 'fees.view.children' },
    stats: [['Collected', '₹18.4L', '+8.2%'], ['Pending', '₹4.2L', '-3.4%'], ['Paid students', '1,084', '+5.1%'], ['Overdue', '83', '-9.7%']],
    columns: ['Student', 'Class', 'Total fee', 'Paid', 'Status'],
    rows: [['Aarav Sharma', '10-A', '₹42,000', '₹42,000', 'Paid'], ['Anaya Patel', '9-B', '₹39,000', '₹30,000', 'Partial'], ['Vivaan Mehta', '8-A', '₹36,000', '₹36,000', 'Paid'], ['Diya Shah', '10-B', '₹42,000', '₹28,000', 'Due'], ['Arjun Rao', '7-C', '₹34,000', '₹34,000', 'Paid']],
    actions: ['Record payment', 'Create receipt', 'Fee report'],
  },
  reports: {
    title: 'Reports & Analytics', eyebrow: 'INSIGHTS', description: 'View academic, attendance, finance and operational reports.', icon: BarChart3,
    permissionByRole: { principal: 'reports.view', accountant: 'financialReports.view' },
    stats: [['Reports generated', '128', '+14%'], ['Attendance', '89.8%', '+2.4%'], ['Fee collection', '81.4%', '+6.8%'], ['Academic avg.', '78.6%', '+3.1%']],
    columns: ['Report', 'Category', 'Period', 'Updated', 'Action'],
    rows: [['Attendance summary', 'Attendance', 'This week', '10 min ago', 'Open'], ['Fee collection', 'Finance', 'September', '32 min ago', 'Open'], ['Exam performance', 'Academic', 'Term 1', '2 hrs ago', 'Open'], ['Staff attendance', 'HR', 'September', 'Today', 'Open'], ['Student strength', 'Students', '2026-27', 'Yesterday', 'Open']],
    actions: ['Create report', 'Schedule report', 'Export data'],
  },
  assignments: {
    title: 'Assignments', eyebrow: 'LEARNING', description: 'Create, distribute and track assignments across assigned classes.', icon: FileText,
    permissionByRole: { teacher: 'assignments.manage.assigned', student: 'assignments.view.own', parent: 'assignments.view.children' },
    stats: [['Active', '24', '+4'], ['Due this week', '11', '+2'], ['Submitted', '86%', '+5.1%'], ['Needs review', '18', '-3']],
    columns: ['Assignment', 'Subject', 'Class', 'Due date', 'Status'],
    rows: [['Algebra worksheet', 'Mathematics', '10-A', '29 Sep', 'Active'], ['Motion project', 'Science', '9-B', '30 Sep', 'Active'], ['Essay writing', 'English', '8-A', '01 Oct', 'Review'], ['HTML basics', 'Computer', '7-C', '03 Oct', 'Active'], ['Civics notes', 'Social Science', '10-B', '04 Oct', 'Active']],
    actions: ['Create assignment', 'Review submissions', 'View calendar'],
  },
  exams: {
    title: 'Exams & Marks', eyebrow: 'ASSESSMENT', description: 'Manage exam schedules, marks entry and assessment workflows.', icon: FileText,
    permissionByRole: { principal: 'exams.manage', teacher: 'exams.manage.assigned', student: 'exams.view.own', parent: 'exams.view.children' },
    stats: [['Upcoming exams', '6', '+2'], ['Marks pending', '38', '-12'], ['Published', '14', '+4'], ['Average score', '78.6%', '+3.1%']],
    columns: ['Exam', 'Subject', 'Class', 'Date', 'Status'],
    rows: [['Mid-term', 'Mathematics', '10-A', '03 Oct', 'Scheduled'], ['Mid-term', 'Science', '10-A', '05 Oct', 'Scheduled'], ['Unit Test', 'English', '9-B', '07 Oct', 'Marks pending'], ['Unit Test', 'Computer', '8-A', '08 Oct', 'Scheduled'], ['Term Assessment', 'SST', '10-B', '10 Oct', 'Scheduled']],
    actions: ['Create exam', 'Enter marks', 'Publish results'],
  },
  results: {
    title: 'Results', eyebrow: 'ACADEMIC PERFORMANCE', description: 'Review published results, grades and student performance trends.', icon: BarChart3,
    permissionByRole: { student: 'results.view.own', parent: 'results.view.children' },
    stats: [['Overall average', '78.6%', '+3.1%'], ['Subjects cleared', '6/6', ''], ['Highest grade', 'A1', ''], ['Improvement', '+4.2%', '+4.2%']],
    columns: ['Subject', 'Assessment', 'Marks', 'Grade', 'Trend'],
    rows: [['Mathematics', 'Mid-term', '86/100', 'A1', 'Up'], ['Science', 'Mid-term', '79/100', 'A2', 'Up'], ['English', 'Mid-term', '82/100', 'A1', 'Stable'], ['Computer', 'Unit Test', '91/100', 'A1', 'Up'], ['Social Science', 'Mid-term', '74/100', 'B1', 'Up']],
    actions: ['View report card', 'Download result'],
  },
  children: {
    title: 'My Children', eyebrow: 'FAMILY PORTAL', description: 'View your children’s attendance, academics, schedule and fees.', icon: Users,
    permissionByRole: { parent: 'children.view.own' },
    stats: [['Children', '2', ''], ['Attendance', '93.2%', '+1.8%'], ['Assignments', '4', '-2'], ['Fee due', '₹12,000', '-6.4%']],
    columns: ['Student', 'Class', 'Attendance', 'Average', 'Fee status'],
    rows: [['Aarav Sharma', '10-A', '96%', '84.2%', 'Paid'], ['Aanya Sharma', '6-B', '90%', '79.8%', '₹12,000 due']],
    actions: ['View child profile', 'Contact school'],
  },
  'my-classes': {
    title: 'My Classes', eyebrow: 'TEACHING', description: 'See assigned classes, student strength and teaching schedule.', icon: School,
    permissionByRole: { teacher: 'classes.view.assigned' },
    stats: [['Assigned classes', '8', '+1'], ['Students', '286', '+12'], ['Subjects', '3', ''], ['Avg. attendance', '91.4%', '+2.2%']],
    columns: ['Class', 'Subject', 'Students', 'Next period', 'Attendance'],
    rows: [['10-A', 'Mathematics', '36', '09:00', '94.4%'], ['10-B', 'Mathematics', '34', '10:00', '91.2%'], ['9-A', 'Mathematics', '35', '11:30', '94.3%'], ['8-A', 'Mathematics', '32', '13:00', '90.6%']],
    actions: ['Open class', 'Mark attendance', 'View timetable'],
  },
  'my-students': {
    title: 'My Students', eyebrow: 'TEACHING', description: 'Track assigned students and identify attendance or academic concerns.', icon: Users,
    permissionByRole: { teacher: 'students.view.assigned' },
    stats: [['Students', '286', '+12'], ['Attendance', '91.4%', '+2.2%'], ['Needs attention', '14', '-3'], ['Assignments due', '18', '+4']],
    columns: ['Student', 'Class', 'Attendance', 'Average', 'Status'],
    rows: [['Aarav Sharma', '10-A', '96%', '84%', 'Good'], ['Anaya Patel', '10-A', '92%', '81%', 'Good'], ['Vivaan Mehta', '10-B', '88%', '76%', 'Watch'], ['Diya Shah', '10-B', '79%', '68%', 'Attention']],
    actions: ['Open student', 'Attendance report', 'Academic notes'],
  },
  profile: {
    title: 'My Profile', eyebrow: 'ACCOUNT', description: 'Manage your personal information, contact details and account preferences.', icon: Settings,
    permissionByRole: { principal: 'profile.manage.own', teacher: 'profile.manage.own', student: 'profile.manage.own', parent: 'profile.manage.own', accountant: 'profile.manage.own' },
    stats: [['Account', 'Active', ''], ['Last login', 'Today', ''], ['Notifications', '4', '-2'], ['Security', 'Good', '']],
    columns: ['Information', 'Current value', 'Status'],
    rows: [['Full name', 'Demo User', 'Verified'], ['Email', 'demo@school.com', 'Verified'], ['Phone', '+91 98XXXXXX21', 'Verified'], ['Academic session', '2026-27', 'Active']],
    actions: ['Edit profile', 'Change password', 'Notification settings'],
  },
  notices: {
    title: 'Notices & Announcements', eyebrow: 'COMMUNICATION', description: 'Publish important school announcements and keep every stakeholder informed.', icon: Megaphone,
    permissionByRole: { principal: 'notices.manage', teacher: 'notices.view', student: 'notices.view', parent: 'notices.view' },
    stats: [['Published', '28', '+6'], ['This month', '8', '+2'], ['Drafts', '3', '-1'], ['Views', '4.8K', '+12%']],
    columns: ['Notice', 'Audience', 'Published', 'Views', 'Status'],
    rows: [['Parent-Teacher Meeting', 'Parents', 'Today', '428', 'Published'], ['Mid-term examination schedule', 'All', 'Yesterday', '1,124', 'Published'], ['Sports day registration', 'Students', '25 Sep', '682', 'Published'], ['Staff meeting update', 'Teachers', '24 Sep', '64', 'Published']],
    actions: ['Create notice', 'Schedule notice', 'View drafts'],
  },
  events: {
    title: 'Events & Calendar', eyebrow: 'SCHOOL LIFE', description: 'Plan school events, meetings, holidays and important dates.', icon: CalendarDays,
    permissionByRole: { principal: 'events.manage', teacher: 'events.view', student: 'events.view', parent: 'events.view' },
    stats: [['Upcoming', '12', '+3'], ['This week', '4', '+1'], ['Meetings', '6', ''], ['Holidays', '2', '']],
    columns: ['Event', 'Date', 'Location', 'Audience', 'Status'],
    rows: [['Parent-Teacher Meeting', '30 Sep', 'Room 204', 'Parents', 'Scheduled'], ['Mid-term examinations', '03 Oct', 'Campus', 'Students', 'Scheduled'], ['Annual sports day', '06 Oct', 'Main ground', 'All', 'Scheduled'], ['Academic review', '08 Oct', 'Principal office', 'Staff', 'Scheduled']],
    actions: ['Create event', 'Add holiday', 'View calendar'],
  },
  payroll: {
    title: 'Payroll', eyebrow: 'STAFF FINANCE', description: 'Track staff payroll, salary processing and payment status.', icon: ReceiptIndianRupee,
    permissionByRole: { principal: 'payroll.manage', accountant: 'payroll.manage' },
    stats: [['Monthly payroll', '₹24.8L', '+4.1%'], ['Processed', '64', '+6'], ['Pending', '4', '-2'], ['Deductions', '₹1.2L', '+1.4%']],
    columns: ['Employee', 'Department', 'Net salary', 'Pay date', 'Status'],
    rows: [['Priya Nair', 'Mathematics', '₹68,000', '30 Sep', 'Processed'], ['Rahul Verma', 'Science', '₹64,000', '30 Sep', 'Processed'], ['Sneha Kapoor', 'English', '₹61,000', '30 Sep', 'Processed'], ['Amit Joshi', 'Computer', '₹58,000', '30 Sep', 'Pending']],
    actions: ['Process payroll', 'View payslips', 'Payroll report'],
  },
}
