import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, Clock3, Save, UserCheck, Users, X } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'
import apiClient from '../../api/client'
import './ModuleFeature.css'
import './AttendanceTimetable.css'

const STATUS = { present:{label:'Present'}, absent:{label:'Absent'}, late:{label:'Late'}, half_day:{label:'Half day'} }
const today = new Date().toISOString().slice(0,10)

function AttendancePage(){
  const {user}=useAuth(); const isPrincipal=user?.role==='principal'; const isTeacher=user?.role==='teacher'; const isParent=user?.role==='parent'; const readOnly=!isPrincipal&&!isTeacher
  const [years,setYears]=useState([]); const [classes,setClasses]=useState([]); const [sections,setSections]=useState([]); const [assignments,setAssignments]=useState([]); const [children,setChildren]=useState([]); const [selectedClass,setSelectedClass]=useState(''); const [selectedSection,setSelectedSection]=useState(''); const [selectedChild,setSelectedChild]=useState(''); const [date,setDate]=useState(today); const [students,setStudents]=useState([]); const [summary,setSummary]=useState(null); const [canEdit,setCanEdit]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('')
  const activeYear=useMemo(()=>years.find((year)=>year.isActive)||years[0]||null,[years]); const availableSections=useMemo(()=>sections.filter((section)=>(section.class?._id||section.class)===selectedClass),[sections,selectedClass]); const selectedClassName=classes.find((item)=>item._id===selectedClass)?.name||''

  const loadSetup=async()=>{setLoading(true);try{const yearRes=await apiClient.get('/academic/years');const nextYears=yearRes.data.years||[];setYears(nextYears);const year=nextYears.find((item)=>item.isActive)||nextYears[0];if(!year)return;const requests=[apiClient.get('/academic/classes',{params:{academicYear:year._id}}),apiClient.get('/academic/sections',{params:{academicYear:year._id}})];if(isTeacher)requests.push(apiClient.get('/academic/teacher-assignments',{params:{academicYear:year._id,teacherId:user.id}}));if(isParent)requests.push(apiClient.get('/parents/me/children'));const results=await Promise.all(requests);setClasses(results[0].data.classes||[]);setSections(results[1].data.sections||[]);if(isTeacher){const nextAssignments=results[2].data.assignments||[];setAssignments(nextAssignments);const first=nextAssignments.find((item)=>item.section);if(first){setSelectedClass(first.class?._id||first.class);setSelectedSection(first.section?._id||first.section)}}if(isParent){const nextChildren=results[2].data.children||[];setChildren(nextChildren);if(!selectedChild&&nextChildren[0])setSelectedChild(nextChildren[0]._id)}if(isPrincipal&&!selectedClass&&results[0].data.classes?.[0])setSelectedClass(results[0].data.classes[0]._id)}catch(err){setError(err.response?.data?.message||'Unable to load attendance setup.')}finally{setLoading(false)}}
  const loadRegister=async()=>{try{const params={date};if(activeYear?._id)params.academicYear=activeYear._id;if(isPrincipal||isTeacher)params.sectionId=selectedSection;if(isParent&&selectedChild)params.studentId=selectedChild;const response=await apiClient.get('/attendance',{params});setStudents(response.data.students||[]);setCanEdit(Boolean(response.data.canEdit));if((user?.role==='student')||(isParent&&selectedChild)){const summaryRes=await apiClient.get('/attendance/summary',{params:{studentId:selectedChild||user.id}});setSummary(summaryRes.data)}}catch(err){setError(err.response?.data?.message||'Unable to load attendance.')}}
  useEffect(()=>{loadSetup()},[user?.role]); useEffect(()=>{if(activeYear&&(isPrincipal?selectedSection:isTeacher?selectedSection:isParent?selectedChild:true))loadRegister()},[activeYear?._id,selectedSection,selectedChild,date])

  const updateStatus=(userId,status)=>{setStudents((current)=>current.map((student)=>student.userId===userId?{...student,status}:student))}
  const save=async()=>{if(!selectedSection)return setError('Select a section first.');setSaving(true);try{await apiClient.post('/attendance/session',{academicYear:activeYear._id,section:selectedSection,date,records:students.map((student)=>({student:student.userId,status:student.status,note:student.note}))});setNotice('Attendance saved successfully.');await loadRegister()}catch(err){setError(err.response?.data?.message||'Unable to save attendance.')}finally{setSaving(false)}}
  const counts=students.reduce((acc,student)=>({...acc,[student.status]:(acc[student.status]||0)+1}),{present:0,absent:0,late:0,half_day:0}); const percentage=students.length?Math.round(((counts.present+counts.late+counts.half_day*.5)/students.length)*1000)/10:0

  return <div className="feature-page attendance-feature-page"><header className="feature-page-heading"><div className="feature-heading-copy"><span className="feature-eyebrow">DAILY OPERATIONS</span><div className="feature-title-line"><div className="feature-title-icon"><UserCheck size={23}/></div><div><h1>Attendance</h1><p>{isPrincipal?'Take or review the real class register.':isTeacher?'Class teachers can save the daily register for their assigned sections.':'View attendance directly from the school records.'}</p></div></div></div>{loading&&<div className="feature-heading-meta"><Clock3 size={14}/> Loading</div>}</header>{error&&<div className="feature-alert error"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="feature-alert success"><Check size={15}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {(isPrincipal||isTeacher)&&<section className="feature-controls-card attendance-controls"><div className="feature-select-grid"><label><span>Class</span><select value={selectedClass} onChange={(e)=>{setSelectedClass(e.target.value);setSelectedSection('')}} disabled={isTeacher}>{classes.map((item)=><option key={item._id} value={item._id}>Class {item.name}</option>)}</select></label><label><span>Section</span><select value={selectedSection} onChange={(e)=>setSelectedSection(e.target.value)}><option value="">Select section</option>{(isTeacher?assignments.filter((item)=>item.section):availableSections).map((item)=><option key={item.section?._id||item._id} value={item.section?._id||item._id}>Section {item.section?.name||item.name}</option>)}</select></label><label><span>Date</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label></div></section>}
    {isParent&&<section className="feature-controls-card"><label><span>Child</span><select value={selectedChild} onChange={(e)=>setSelectedChild(e.target.value)}>{children.map((child)=><option key={child._id} value={child._id}>{child.name} · {child.admissionNumber}</option>)}</select></label><label><span>Date</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label></section>}
    {(isPrincipal||isTeacher)&&<section className="feature-stat-grid"><article><span>Attendance</span><strong>{percentage}%</strong><small><UserCheck size={13}/> Current register</small></article><article><span>Present</span><strong className="feature-good">{counts.present||0}</strong><small><Check size={13}/> Students present</small></article><article><span>Absent</span><strong className="feature-bad">{counts.absent||0}</strong><small><X size={13}/> Students absent</small></article><article><span>Late / half day</span><strong className="feature-warn">{(counts.late||0)+(counts.half_day||0)}</strong><small><Clock3 size={13}/> Exceptions</small></article></section>}
    {summary&&<section className="feature-stat-grid"><article><span>Attendance</span><strong>{summary.percentage}%</strong><small><UserCheck size={13}/> Personal record</small></article><article><span>Present</span><strong className="feature-good">{summary.present}</strong><small>Days present</small></article><article><span>Absent</span><strong className="feature-bad">{summary.absent}</strong><small>Days absent</small></article><article><span>Late</span><strong className="feature-warn">{summary.late}</strong><small>Late days</small></article></section>}
    {(isPrincipal||isTeacher)&&<section className="feature-panel attendance-panel"><div className="feature-panel-header"><div><span className="feature-eyebrow">DAILY REGISTER</span><h2>Class {selectedClassName || '—'} · {availableSections.find((item)=>item._id===selectedSection)?.name||assignments.find((item)=>(item.section?._id||item.section)===selectedSection)?.section?.name||'—'}</h2><p>{students.length} real students · {new Date(`${date}T00:00:00`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div>{canEdit&&<button className="primary-button" onClick={save} disabled={saving}><Save size={15}/> {saving?'Saving...':'Save attendance'}</button>}</div><div className="attendance-table-wrap"><table className="feature-table attendance-edit-table"><thead><tr><th>Student</th><th>Admission</th><th>Roll</th><th>Status</th><th>Note</th></tr></thead><tbody>{students.map((student)=><tr key={student.userId}><td><div className="person-cell"><div className="person-avatar">{student.name?.split(' ').map((part)=>part[0]).join('').slice(0,2)}</div><strong>{student.name}</strong></div></td><td>{student.admissionNumber}</td><td>{student.rollNumber}</td><td><div className="attendance-status-actions">{Object.entries(STATUS).map(([key,meta])=><button key={key} type="button" disabled={!canEdit} className={`attendance-choice ${student.status===key?`selected ${key}`:''}`} onClick={()=>updateStatus(student.userId,key)}>{meta.label}</button>)}</div></td><td><input className="attendance-note-input" disabled={!canEdit} value={student.note||''} onChange={(e)=>setStudents((current)=>current.map((item)=>item.userId===student.userId?{...item,note:e.target.value}:item))} placeholder="Optional note"/></td></tr>)}</tbody></table>{!students.length&&<div className="empty-state"><Users size={22}/><strong>No students are enrolled in this section.</strong><span>Enroll students from the principal's Students page first.</span></div>}</div></section>}
    {(user?.role==='student'||isParent)&&<section className="feature-panel attendance-panel"><div className="feature-panel-header"><div><span className="feature-eyebrow">ATTENDANCE HISTORY</span><h2>{isParent?'Child attendance':'My attendance'}</h2><p>Attendance is calculated from saved daily registers.</p></div></div><div className="attendance-status-strip"><div><span className="attendance-dot present-dot"/><strong>{summary?.present||0}</strong><span>Present</span></div><div><span className="attendance-dot absent-dot"/><strong>{summary?.absent||0}</strong><span>Absent</span></div><div><span className="attendance-dot late-dot"/><strong>{summary?.late||0}</strong><span>Late</span></div><div><span className="attendance-dot halfday-dot"/><strong>{summary?.halfDay||0}</strong><span>Half day</span></div></div></section>}
  </div>
}
export default AttendancePage
