import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, Clock3, Loader2, MapPin, Plus, RefreshCw, Trash2, UserRound, X } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'
import apiClient from '../../api/client'
import './ModuleFeature.css'
import './AttendanceTimetable.css'

const DAYS = ['monday','tuesday','wednesday','thursday','friday','saturday']
const DAY_LABELS = { monday:'Monday', tuesday:'Tuesday', wednesday:'Wednesday', thursday:'Thursday', friday:'Friday', saturday:'Saturday' }
const PERIODS = [['08:00','08:45'],['08:45','09:30'],['09:45','10:30'],['10:30','11:15'],['11:30','12:15'],['12:15','13:00']]

function TimetablePage() {
  const { user } = useAuth(); const isPrincipal = user?.role === 'principal'
  const [years,setYears]=useState([]); const [classes,setClasses]=useState([]); const [sections,setSections]=useState([]); const [teachers,setTeachers]=useState([]); const [subjects,setSubjects]=useState([]); const [entries,setEntries]=useState([]); const [children,setChildren]=useState([])
  const [selectedClass,setSelectedClass]=useState(''); const [selectedSection,setSelectedSection]=useState(''); const [selectedChild,setSelectedChild]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [showAdd,setShowAdd]=useState(false)
  const [form,setForm]=useState({ day:'monday', periodNumber:1, subject:'', teacher:'', room:'' })
  const activeYear=useMemo(()=>years.find((year)=>year.isActive)||years[0]||null,[years]); const filteredSections=useMemo(()=>sections.filter((section)=>(section.class?._id||section.class)===selectedClass),[sections,selectedClass]); const classSubjects=useMemo(()=>subjects.filter((item)=>(item.class?._id||item.class)===selectedClass),[subjects,selectedClass])

  const load = async () => { setLoading(true); setError(''); try { const yearRes=await apiClient.get('/academic/years'); const nextYears=yearRes.data.years||[]; setYears(nextYears); const year=nextYears.find((item)=>item.isActive)||nextYears[0]; if (!year) return; const requests=[apiClient.get('/academic/classes',{params:{academicYear:year._id}}),apiClient.get('/academic/sections',{params:{academicYear:year._id}}),apiClient.get('/teachers'),apiClient.get('/subjects',{params:{academicYear:year._id}})]; if(user?.role==='parent') requests.push(apiClient.get('/parents/me/children')); const results=await Promise.all(requests); setClasses(results[0].data.classes||[]); setSections(results[1].data.sections||[]); setTeachers(results[2].data.teachers||[]); setSubjects(results[3].data.subjects||[]); if(user?.role==='parent') { const nextChildren=results[4].data.children||[]; setChildren(nextChildren); if(!selectedChild&&nextChildren[0]) setSelectedChild(nextChildren[0]._id) } if(isPrincipal && !selectedClass && results[0].data.classes?.[0]) setSelectedClass(results[0].data.classes[0]._id); } catch(err){setError(err.response?.data?.message||'Unable to load timetable setup.')} finally{setLoading(false)} }
  const loadEntries=async()=>{ try { const params=activeYear?._id?{academicYear:activeYear._id}:{}; if(isPrincipal&&selectedSection) params.sectionId=selectedSection; if(!isPrincipal&&user?.role==='parent'&&selectedChild) params.studentId=selectedChild; const response=await apiClient.get('/timetable',{params}); setEntries(response.data.entries||[]) } catch(err){setError(err.response?.data?.message||'Unable to load timetable.')} }
  useEffect(()=>{load()},[user?.role]); useEffect(()=>{if(activeYear) loadEntries()},[activeYear?._id,selectedSection,selectedChild])

  const autoGenerate=async()=>{ if(!selectedSection||!activeYear) return setError('Select a class and section first.'); setSaving(true); setError(''); try { const response=await apiClient.post('/timetable/auto-generate',{academicYear:activeYear._id,section:selectedSection}); const messages=[]; if(response.data.missingTeachers?.length) messages.push(`Missing teacher: ${response.data.missingTeachers.join(', ')}`); if(response.data.conflicts?.length) messages.push(...response.data.conflicts); setNotice(messages.length?`Generated ${response.data.createdCount} periods. ${messages.join(' ')}`:`Generated ${response.data.createdCount} draft periods without teacher conflicts.`); await loadEntries() } catch(err){setError(err.response?.data?.message||'Unable to generate timetable.')} finally{setSaving(false)} }
  const publishAll=async()=>{ const drafts=entries.filter((entry)=>entry.status!=='published'); if(!drafts.length) return setNotice('This timetable is already published.'); setSaving(true); try { for(const entry of drafts) await apiClient.patch(`/timetable/${entry._id}/publish`); setNotice('Timetable published successfully.'); await loadEntries() } catch(err){setError(err.response?.data?.message||'Unable to publish timetable.')} finally{setSaving(false)} }
  const addEntry=async()=>{ if(!selectedSection||!activeYear||!form.subject||!form.teacher) return setError('Select class, section, subject and teacher.'); const [startTime,endTime]=PERIODS[Number(form.periodNumber)-1]; setSaving(true); try { await apiClient.post('/timetable',{academicYear:activeYear._id,section:selectedSection,teacher:form.teacher,subject:form.subject,day:form.day,periodNumber:Number(form.periodNumber),startTime,endTime,room:form.room,status:'draft'}); setNotice('Timetable period added.'); setShowAdd(false); await loadEntries() } catch(err){setError(err.response?.data?.message||'Unable to add period.')} finally{setSaving(false)} }
  const deleteEntry=async(entry)=>{if(!window.confirm('Delete this timetable period?'))return;try{await apiClient.delete(`/timetable/${entry._id}`);setNotice('Period deleted.');await loadEntries()}catch(err){setError(err.response?.data?.message||'Unable to delete period.')}}
  const selectedSectionName=filteredSections.find((section)=>section._id===selectedSection)?.name||''; const selectedClassName=classes.find((item)=>item._id===selectedClass)?.name||''
  const entryMap=useMemo(()=>new Map(entries.map((entry)=>[`${entry.day}:${entry.periodNumber}`,entry])),[entries])

  return <div className="feature-page timetable-feature-page"><header className="feature-page-heading"><div className="feature-heading-copy"><span className="feature-eyebrow">SCHOOL SCHEDULE</span><div className="feature-title-line"><div className="feature-title-icon"><CalendarDays size={23}/></div><div><h1>Timetable</h1><p>{isPrincipal?'Select any class and section, generate the weekly schedule, review conflicts and publish it.':'Your timetable is loaded from the school schedule set by the principal.'}</p></div></div></div>{loading&&<div className="feature-heading-meta"><Loader2 size={14}/> Loading</div>}</header>{error&&<div className="feature-alert error"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="feature-alert success"><Check size={15}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {isPrincipal&&<section className="feature-controls-card timetable-controls-card"><div className="feature-select-grid"><label><span>Class</span><select value={selectedClass} onChange={(e)=>{setSelectedClass(e.target.value);setSelectedSection('')}}><option value="">Select class</option>{classes.map((item)=><option key={item._id} value={item._id}>Class {item.name}</option>)}</select></label><label><span>Section</span><select value={selectedSection} onChange={(e)=>setSelectedSection(e.target.value)}><option value="">Select section</option>{filteredSections.map((item)=><option key={item._id} value={item._id}>Section {item.name}</option>)}</select></label><div className="feature-selection-summary"><span>Selected schedule</span><strong>{selectedClassName&&selectedSectionName?`Class ${selectedClassName} · Section ${selectedSectionName}`:'Choose class and section'}</strong><small>{activeYear?.name||'No active academic year'}</small></div></div><div className="timetable-action-row"><button className="secondary-button" type="button" onClick={load}><RefreshCw size={15}/> Refresh</button><button className="secondary-button" type="button" onClick={autoGenerate} disabled={saving||!selectedSection}><CalendarDays size={15}/> Auto generate</button><button className="secondary-button" type="button" onClick={()=>setShowAdd(true)} disabled={!selectedSection}><Plus size={15}/> Add period</button><button className="primary-button" type="button" onClick={publishAll} disabled={saving||!selectedSection}><Check size={15}/> Publish timetable</button></div></section>}
    {user?.role==='parent'&&<section className="feature-controls-card"><label><span>Child</span><select value={selectedChild} onChange={(e)=>setSelectedChild(e.target.value)}>{children.map((child)=><option key={child._id} value={child._id}>{child.name} · {child.admissionNumber}</option>)}</select></label></section>}
    <section className="feature-stat-grid"><article><span>Days</span><strong>6</strong><small><CalendarDays size={13}/> Monday to Saturday</small></article><article><span>Periods / day</span><strong>6</strong><small><Clock3 size={13}/> Fixed school slots</small></article><article><span>Lessons loaded</span><strong>{entries.length}</strong><small><UserRound size={13}/> Real timetable entries</small></article><article><span>Status</span><strong className="feature-good">{entries.length&&entries.every((entry)=>entry.status==='published')?'Published':'Draft'}</strong><small><Check size={13}/> Database schedule</small></article></section>
    <section className="feature-panel timetable-panel"><div className="feature-panel-header"><div><span className="feature-eyebrow">WEEKLY VIEW</span><h2>{isPrincipal&&selectedClassName?`Class ${selectedClassName} · Section ${selectedSectionName||'—'}`:user?.role==='teacher'?`${user.name} · Weekly timetable`:user?.role==='parent'?'Child timetable':'My weekly timetable'}</h2><p>Every period comes from the real timetable collection.</p></div><span className="feature-live-badge">Mon–Sat</span></div><div className="timetable-scroll"><div className="timetable-grid timetable-six-day-grid" style={{'--day-count':DAYS.length}}><div className="timetable-corner">Period</div>{DAYS.map((day)=><div className="timetable-day" key={day}><strong>{DAY_LABELS[day].slice(0,3)}</strong><span>{DAY_LABELS[day]}</span></div>)}{PERIODS.map(([start,end],index)=><div className="timetable-grid-row" key={start}><div className="timetable-period"><strong>{start}</strong><span>{end}</span></div>{DAYS.map((day)=>{const entry=entryMap.get(`${day}:${index+1}`);return <div className={`timetable-cell ${!entry?'free':''}`} key={`${day}-${index}`}>{entry?<><strong>{entry.subject?.name||'Subject'}</strong><span><UserRound size={12}/> {entry.teacher?.name||'Teacher'}</span><small><MapPin size={11}/> {entry.room||'Room not set'}</small>{isPrincipal&&<button className="timetable-cell-delete" onClick={()=>deleteEntry(entry)}><Trash2 size={11}/></button>}</>:<span className="free-label">Free period</span>}</div>})}</div>)}</div></div></section>
    {showAdd&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><span>TIMETABLE SETUP</span><h2>Add period</h2></div><button className="icon-btn" onClick={()=>setShowAdd(false)}><X size={17}/></button></div><div className="modal-body"><div className="form-grid"><label className="form-field"><span>Day</span><select value={form.day} onChange={(e)=>setForm({...form,day:e.target.value})}>{DAYS.map((day)=><option key={day} value={day}>{DAY_LABELS[day]}</option>)}</select></label><label className="form-field"><span>Period</span><select value={form.periodNumber} onChange={(e)=>setForm({...form,periodNumber:e.target.value})}>{PERIODS.map(([start,end],index)=><option key={start} value={index+1}>Period {index+1} · {start}-{end}</option>)}</select></label><label className="form-field"><span>Subject</span><select value={form.subject} onChange={(e)=>setForm({...form,subject:e.target.value})}><option value="">Select subject</option>{classSubjects.map((item)=><option key={item.subject?._id||item._id} value={item.subject?._id||item._id}>{item.subject?.name||item.name}</option>)}</select></label><label className="form-field"><span>Teacher</span><select value={form.teacher} onChange={(e)=>setForm({...form,teacher:e.target.value})}><option value="">Select teacher</option>{teachers.map((teacher)=><option key={teacher.user} value={teacher.user}>{teacher.name}</option>)}</select></label><label className="form-field"><span>Room</span><input value={form.room} onChange={(e)=>setForm({...form,room:e.target.value})} placeholder="204"/></label></div></div><div className="modal-foot"><button className="secondary-btn" onClick={()=>setShowAdd(false)} disabled={saving}>Cancel</button><button className="primary-btn" onClick={addEntry} disabled={saving}>{saving?<Loader2 size={15} className="spin"/>:<Plus size={15}/>} {saving?'Saving...':'Add period'}</button></div></div></div>}
  </div>
}
export default TimetablePage
